version: '3'

services:
  # Database
  mysql:
    image: 'mysql:5.7'
    container_name: 'typeorm-mysql'
    restart: always
    env_file: 
      - .env
    volumes: 
      - ./data:/var/lib/mysql
    ports: 
      - "3306:3306"
    networks:
      - default
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - .env
    networks:
      - default
  
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  redis:
    image: 'redis:5.0.7-alpine'
    ports: 
      - '6379:6379'
    networks: 
      - default

networks:
  default:
    external:
      name: sample
